version: '3.8'

services:
  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    ports: ["9092:9092"]
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    depends_on:
      - zookeeper
    stop_grace_period: 30s

  zookeeper:
    image: wurstmeister/zookeeper
    ports: ["2181:2181"]

  api:
    build: ./api
    ports: ["8000:8000"]
    depends_on: [kafka]

  booking-worker:
    build: ./worker
    depends_on: [kafka]
    deploy:
      replicas: 4