version: '3.8'

services:
  # 1. Kafka (брокер)
  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    ports: ["9092:9092"]
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports: ["2181:2181"]

  # 2. API Gateway (1 контейнер)
  api:
    build: ./api
    ports: ["8000:8000"]
    depends_on: [kafka]

  # 3. Воркеры (МНОГО реплик одного типа!)
  booking-worker:
    build: ./worker
    depends_on: [kafka]
    deploy:
      replicas: 4  # ← Горизонтальное масштабирование!